In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df  = pd.read_csv('https://raw.githubusercontent.com/microsoft/ML-For-Beginners/main/3-Web-App/1-Web-App/data/ufos.csv')

In [3]:
df

datetime                  city state country     shape  \
0      10/10/1949 20:30            san marcos    tx      us  cylinder   
1      10/10/1949 21:00          lackland afb    tx     NaN     light   
2      10/10/1955 17:00  chester (uk/england)   NaN      gb    circle   
3      10/10/1956 21:00                  edna    tx      us    circle   
4      10/10/1960 20:00               kaneohe    hi      us     light   
...                 ...                   ...   ...     ...       ...   
80327    9/9/2013 21:15             nashville    tn      us     light   
80328    9/9/2013 22:00                 boise    id      us    circle   
80329    9/9/2013 22:00                  napa    ca      us     other   
80330    9/9/2013 22:20                vienna    va      us    circle   
80331    9/9/2013 23:00                edmond    ok      us     cigar   

       duration (seconds) duration (hours/min)  \
0                  2700.0           45 minutes   
1                  7200.0              1-2 hrs   
2                    20.0           20 seconds   
3                    20.0             1/2 hour   
4                   900.0           15 minutes   
...                   ...                  ...   
80327               600.0           10 minutes   
80328              1200.0           20 minutes   
80329              1200.0                 hour   
80330                 5.0            5 seconds   
80331              1020.0           17 minutes   

                                                comments date posted  \
0      This event took place in early fall around 194...   4/27/2004   
1      1949 Lackland AFB&#44 TX.  Lights racing acros...  12/16/2005   
2      Green/Orange circular disc over Chester&#44 En...   1/21/2008   
3      My older brother and twin sister were leaving ...   1/17/2004   
4      AS a Marine 1st Lt. flying an FJ4B fighter/att...   1/22/2004   
...                                                  ...         ...   
80327  Round from the distance/slowly changing colors...   9/30/2013   
80328  Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...   9/30/2013   
80329                                       Napa UFO&#44   9/30/2013   
80330  Saw a five gold lit cicular craft moving fastl...   9/30/2013   
80331  2 witnesses 2  miles apart&#44 Red &amp; White...   9/30/2013   

        latitude   longitude  
0      29.883056  -97.941111  
1      29.384210  -98.581082  
2      53.200000   -2.916667  
3      28.978333  -96.645833  
4      21.418056 -157.803611  
...          ...         ...  
80327  36.165833  -86.784444  
80328  43.613611 -116.202500  
80329  38.297222 -122.284444  
80330  38.901111  -77.265556  
80331  35.652778  -97.477778  

[80332 rows x 11 columns]

In [4]:
df.head()

datetime                  city state country     shape  \
0  10/10/1949 20:30            san marcos    tx      us  cylinder   
1  10/10/1949 21:00          lackland afb    tx     NaN     light   
2  10/10/1955 17:00  chester (uk/england)   NaN      gb    circle   
3  10/10/1956 21:00                  edna    tx      us    circle   
4  10/10/1960 20:00               kaneohe    hi      us     light   

   duration (seconds) duration (hours/min)  \
0              2700.0           45 minutes   
1              7200.0              1-2 hrs   
2                20.0           20 seconds   
3                20.0             1/2 hour   
4               900.0           15 minutes   

                                            comments date posted   latitude  \
0  This event took place in early fall around 194...   4/27/2004  29.883056   
1  1949 Lackland AFB&#44 TX.  Lights racing acros...  12/16/2005  29.384210   
2  Green/Orange circular disc over Chester&#44 En...   1/21/2008  53.200000   
3  My older brother and twin sister were leaving ...   1/17/2004  28.978333   
4  AS a Marine 1st Lt. flying an FJ4B fighter/att...   1/22/2004  21.418056   

    longitude  
0  -97.941111  
1  -98.581082  
2   -2.916667  
3  -96.645833  
4 -157.803611

In [5]:
df.columns

Index(['datetime', 'city', 'state', 'country', 'shape', 'duration (seconds)',
       'duration (hours/min)', 'comments', 'date posted', 'latitude',
       'longitude'],
      dtype='object')

In [7]:
ufos = pd.DataFrame({'Seconds':df['duration (seconds)'],'Country':df['country'],'Latitude':df['latitude'],'Longitude':df['longitude']})
ufos.Country.unique()

array(['us', nan, 'gb', 'ca', 'au', 'de'], dtype=object)

In [8]:
ufos.isna().sum()

Seconds         0
Country      9670
Latitude        0
Longitude       0
dtype: int64

In [10]:
ufos.dropna(inplace=True)

In [12]:
ufos.shape

(70662, 4)

In [15]:
ufos = ufos[(ufos['Seconds'] >=1) & (ufos['Seconds'] <=60)]
ufos

Seconds Country   Latitude   Longitude
2         20.0      gb  53.200000   -2.916667
3         20.0      us  28.978333  -96.645833
14        30.0      us  35.823889  -80.253611
23        60.0      us  45.582778 -122.352222
24         3.0      gb  51.783333   -0.783333
...        ...     ...        ...         ...
80320     60.0      us  33.209722  -87.569167
80321      3.0      us  36.529722  -87.359444
80323     60.0      us  29.651389  -82.325000
80326     20.0      us  34.101389  -84.519444
80330      5.0      us  38.901111  -77.265556

[25863 rows x 4 columns]

In [16]:
ufos.dtypes

Seconds      float64
Country       object
Latitude     float64
Longitude    float64
dtype: object

In [18]:
from sklearn.preprocessing import LabelEncoder
ufos.Country = LabelEncoder().fit_transform(ufos['Country'])
ufos.head()


/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


Seconds  Country   Latitude   Longitude
2      20.0        3  53.200000   -2.916667
3      20.0        4  28.978333  -96.645833
14     30.0        4  35.823889  -80.253611
23     60.0        4  45.582778 -122.352222
24      3.0        3  51.783333   -0.783333

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [20]:
selected_features = ['Seconds','Latitude','Longitude']
X = ufos[selected_features]
y = ufos['Country']

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

In [23]:
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [24]:
predictions = model.predict(X_test)

In [27]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       0.81      0.21      0.34       349
           2       1.00      0.90      0.95        10
           3       0.99      1.00      1.00       179
           4       0.96      1.00      0.98      5875

    accuracy                           0.95      6466
   macro avg       0.95      0.82      0.85      6466
weighted avg       0.95      0.95      0.94      6466



In [28]:
print(confusion_matrix(y_test,predictions))

[[  53    0    0    0    0]
 [   0   74    0    0  275]
 [   0    0    9    1    0]
 [   0    0    0  179    0]
 [   0   17    0    0 5858]]


In [29]:
print(accuracy_score(y_test,predictions))

0.9546860501082586


**Model Pickling**

In [31]:
import pickle

pickle.dump(model,open('ufo-model.pkl','wb'))